// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.4
// source: plugin.proto

package pluginproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	PluginId        string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Cursor) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Cursor) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type DataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *structpb.Struct       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceRequest) Reset() {
	*x = DataSourceRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceRequest) ProtoMessage() {}

func (x *DataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceRequest.ProtoReflect.Descriptor instead.
func (*DataSourceRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *DataSourceRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DataSourceRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *DataSourceRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *DataSourceRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Resource) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FetchedItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalId      string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content         []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	MimeType        string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsDeleted       bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	ReplacesSubtree bool                   `protobuf:"varint,9,opt,name=replaces_subtree,json=replacesSubtree,proto3" json:"replaces_subtree,omitempty"`
	SubtreeKeep     []string               `protobuf:"bytes,10,rep,name=subtree_keep,json=subtreeKeep,proto3" json:"subtree_keep,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchedItem) Reset() {
	*x = FetchedItem{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchedItem) ProtoMessage() {}

func (x *FetchedItem) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchedItem.ProtoReflect.Descriptor instead.
func (*FetchedItem) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FetchedItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FetchedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FetchedItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FetchedItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchedItem) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FetchedItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FetchedItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FetchedItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *FetchedItem) GetReplacesSubtree() bool {
	if x != nil {
		return x.ReplacesSubtree
	}
	return false
}

func (x *FetchedItem) GetSubtreeKeep() []string {
	if x != nil {
		return x.SubtreeKeep
	}
	return nil
}

type DataSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Ancestors     []string               `protobuf:"bytes,3,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	Items         []*FetchedItem         `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Warnings      []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceResponse) Reset() {
	*x = DataSourceResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceResponse) ProtoMessage() {}

func (x *DataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceResponse.ProtoReflect.Descriptor instead.
func (*DataSourceResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *DataSourceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DataSourceResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DataSourceResponse) GetAncestors() []string {
	if x != nil {
		return x.Ancestors
	}
	return nil
}

func (x *DataSourceResponse) GetItems() []*FetchedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DataSourceResponse) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *DataSourceResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ParserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FileContent           []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName              string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType              string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Url                   string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Title                 string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ParserEngine          string                 `protobuf:"bytes,6,opt,name=parser_engine,json=parserEngine,proto3" json:"parser_engine,omitempty"`
	RequestId             string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ParserEngineOverrides map[string]string      `protobuf:"bytes,8,rep,name=parser_engine_overrides,json=parserEngineOverrides,proto3" json:"parser_engine_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ParserRequest) Reset() {
	*x = ParserRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserRequest) ProtoMessage() {}

func (x *ParserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserRequest.ProtoReflect.Descriptor instead.
func (*ParserRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ParserRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ParserRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ParserRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ParserRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ParserRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ParserRequest) GetParserEngine() string {
	if x != nil {
		return x.ParserEngine
	}
	return ""
}

func (x *ParserRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ParserRequest) GetParserEngineOverrides() map[string]string {
	if x != nil {
		return x.ParserEngineOverrides
	}
	return nil
}

type ParserImageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalRef   string                 `protobuf:"bytes,2,opt,name=original_ref,json=originalRef,proto3" json:"original_ref,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	StorageKey    string                 `protobuf:"bytes,4,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,5,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	IsOriginal    bool                   `protobuf:"varint,6,opt,name=is_original,json=isOriginal,proto3" json:"is_original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserImageRef) Reset() {
	*x = ParserImageRef{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserImageRef) ProtoMessage() {}

func (x *ParserImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserImageRef.ProtoReflect.Descriptor instead.
func (*ParserImageRef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ParserImageRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ParserImageRef) GetOriginalRef() string {
	if x != nil {
		return x.OriginalRef
	}
	return ""
}

func (x *ParserImageRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ParserImageRef) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *ParserImageRef) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ParserImageRef) GetIsOriginal() bool {
	if x != nil {
		return x.IsOriginal
	}
	return false
}

type ParserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarkdownContent string                 `protobuf:"bytes,1,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"`
	ImageRefs       []*ParserImageRef      `protobuf:"bytes,2,rep,name=image_refs,json=imageRefs,proto3" json:"image_refs,omitempty"`
	ImageDirPath    string                 `protobuf:"bytes,3,opt,name=image_dir_path,json=imageDirPath,proto3" json:"image_dir_path,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	IsAudio         bool                   `protobuf:"varint,6,opt,name=is_audio,json=isAudio,proto3" json:"is_audio,omitempty"`
	AudioData       []byte                 `protobuf:"bytes,7,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParserResponse) Reset() {
	*x = ParserResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserResponse) ProtoMessage() {}

func (x *ParserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserResponse.ProtoReflect.Descriptor instead.
func (*ParserResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ParserResponse) GetMarkdownContent() string {
	if x != nil {
		return x.MarkdownContent
	}
	return ""
}

func (x *ParserResponse) GetImageRefs() []*ParserImageRef {
	if x != nil {
		return x.ImageRefs
	}
	return nil
}

func (x *ParserResponse) GetImageDirPath() string {
	if x != nil {
		return x.ImageDirPath
	}
	return ""
}

func (x *ParserResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ParserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ParserResponse) GetIsAudio() bool {
	if x != nil {
		return x.IsAudio
	}
	return false
}

func (x *ParserResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type WebSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MaxResults    int32                  `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	IncludeDate   bool                   `protobuf:"varint,3,opt,name=include_date,json=includeDate,proto3" json:"include_date,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EngineId      string                 `protobuf:"bytes,5,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ProxyUrl      string                 `protobuf:"bytes,7,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	ExtraConfig   map[string]string      `protobuf:"bytes,8,rep,name=extra_config,json=extraConfig,proto3" json:"extra_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSearchRequest) Reset() {
	*x = WebSearchRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchRequest) ProtoMessage() {}

func (x *WebSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchRequest.ProtoReflect.Descriptor instead.
func (*WebSearchRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *WebSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *WebSearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *WebSearchRequest) GetIncludeDate() bool {
	if x != nil {
		return x.IncludeDate
	}
	return false
}

func (x *WebSearchRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *WebSearchRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *WebSearchRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *WebSearchRequest) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *WebSearchRequest) GetExtraConfig() map[string]string {
	if x != nil {
		return x.ExtraConfig
	}
	return nil
}

type WebSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSearchResult) Reset() {
	*x = WebSearchResult{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchResult) ProtoMessage() {}

func (x *WebSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchResult.ProtoReflect.Descriptor instead.
func (*WebSearchResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *WebSearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WebSearchResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebSearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *WebSearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WebSearchResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WebSearchResult) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type WebSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*WebSearchResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSearchResponse) Reset() {
	*x = WebSearchResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSearchResponse) ProtoMessage() {}

func (x *WebSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSearchResponse.ProtoReflect.Descriptor instead.
func (*WebSearchResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *WebSearchResponse) GetResults() []*WebSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *WebSearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x11weknora.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x12\n" +
	"\x10HandshakeRequest\"\x7f\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x06Cursor\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xb7\x01\n" +
	"\x11DataSourceRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x121\n" +
	"\x06cursor\x18\x04 \x01(\v2\x19.weknora.plugin.v1.CursorR\x06cursor\"\xf4\x01\n" +
	"\bResource\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12E\n" +
	"\bmetadata\x18\x05 \x03(\v2).weknora.plugin.v1.Resource.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x03\n" +
	"\vFetchedItem\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12H\n" +
	"\bmetadata\x18\a \x03(\v2,.weknora.plugin.v1.FetchedItem.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted\x12)\n" +
	"\x10replaces_subtree\x18\t \x01(\bR\x0freplacesSubtree\x12!\n" +
	"\fsubtree_keep\x18\n" +
	" \x03(\tR\vsubtreeKeep\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\x12DataSourceResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x129\n" +
	"\tresources\x18\x02 \x03(\v2\x1b.weknora.plugin.v1.ResourceR\tresources\x12\x1c\n" +
	"\tancestors\x18\x03 \x03(\tR\tancestors\x124\n" +
	"\x05items\x18\x04 \x03(\v2\x1e.weknora.plugin.v1.FetchedItemR\x05items\x121\n" +
	"\x06cursor\x18\x05 \x01(\v2\x19.weknora.plugin.v1.CursorR\x06cursor\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\"\x97\x03\n" +
	"\rParserRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12#\n" +
	"\rparser_engine\x18\x06 \x01(\tR\fparserEngine\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12s\n" +
	"\x17parser_engine_overrides\x18\b \x03(\v2;.weknora.plugin.v1.ParserRequest.ParserEngineOverridesEntryR\x15parserEngineOverrides\x1aH\n" +
	"\x1aParserEngineOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\x0eParserImageRef\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\foriginal_ref\x18\x02 \x01(\tR\voriginalRef\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vstorage_key\x18\x04 \x01(\tR\n" +
	"storageKey\x12\x1d\n" +
	"\n" +
	"image_data\x18\x05 \x01(\fR\timageData\x12\x1f\n" +
	"\vis_original\x18\x06 \x01(\bR\n" +
	"isOriginal\"\xfd\x02\n" +
	"\x0eParserResponse\x12)\n" +
	"\x10markdown_content\x18\x01 \x01(\tR\x0fmarkdownContent\x12@\n" +
	"\n" +
	"image_refs\x18\x02 \x03(\v2!.weknora.plugin.v1.ParserImageRefR\timageRefs\x12$\n" +
	"\x0eimage_dir_path\x18\x03 \x01(\tR\fimageDirPath\x12K\n" +
	"\bmetadata\x18\x04 \x03(\v2/.weknora.plugin.v1.ParserResponse.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x19\n" +
	"\bis_audio\x18\x06 \x01(\bR\aisAudio\x12\x1d\n" +
	"\n" +
	"audio_data\x18\a \x01(\fR\taudioData\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x10WebSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\x05R\n" +
	"maxResults\x12!\n" +
	"\finclude_date\x18\x03 \x01(\bR\vincludeDate\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x1b\n" +
	"\tengine_id\x18\x05 \x01(\tR\bengineId\x12\x19\n" +
	"\bbase_url\x18\x06 \x01(\tR\abaseUrl\x12\x1b\n" +
	"\tproxy_url\x18\a \x01(\tR\bproxyUrl\x12W\n" +
	"\fextra_config\x18\b \x03(\v24.weknora.plugin.v1.WebSearchRequest.ExtraConfigEntryR\vextraConfig\x1a>\n" +
	"\x10ExtraConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x0fWebSearchResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\tR\vpublishedAt\"g\n" +
	"\x11WebSearchResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".weknora.plugin.v1.WebSearchResultR\aresults\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xdd\x06\n" +
	"\x10DataSourcePlugin\x12V\n" +
	"\tHandshake\x12#.weknora.plugin.v1.HandshakeRequest\x1a$.weknora.plugin.v1.HandshakeResponse\x12M\n" +
	"\x06Health\x12 .weknora.plugin.v1.HealthRequest\x1a!.weknora.plugin.v1.HealthResponse\x12W\n" +
	"\bValidate\x12$.weknora.plugin.v1.DataSourceRequest\x1a%.weknora.plugin.v1.DataSourceResponse\x12\\\n" +
	"\rListResources\x12$.weknora.plugin.v1.DataSourceRequest\x1a%.weknora.plugin.v1.DataSourceResponse\x12g\n" +
	"\x18ResolveResourceAncestors\x12$.weknora.plugin.v1.DataSourceRequest\x1a%.weknora.plugin.v1.DataSourceResponse\x12W\n" +
	"\bFetchAll\x12$.weknora.plugin.v1.DataSourceRequest\x1a%.weknora.plugin.v1.DataSourceResponse\x12_\n" +
	"\x10FetchIncremental\x12$.weknora.plugin.v1.DataSourceRequest\x1a%.weknora.plugin.v1.DataSourceResponse\x12_\n" +
	"\x0eFetchAllStream\x12$.weknora.plugin.v1.DataSourceRequest\x1a%.weknora.plugin.v1.DataSourceResponse0\x01\x12g\n" +
	"\x16FetchIncrementalStream\x12$.weknora.plugin.v1.DataSourceRequest\x1a%.weknora.plugin.v1.DataSourceResponse0\x012\x83\x02\n" +
	"\fParserPlugin\x12V\n" +
	"\tHandshake\x12#.weknora.plugin.v1.HandshakeRequest\x1a$.weknora.plugin.v1.HandshakeResponse\x12M\n" +
	"\x06Health\x12 .weknora.plugin.v1.HealthRequest\x1a!.weknora.plugin.v1.HealthResponse\x12L\n" +
	"\x05Parse\x12 .weknora.plugin.v1.ParserRequest\x1a!.weknora.plugin.v1.ParserResponse2\x8d\x02\n" +
	"\x0fWebSearchPlugin\x12V\n" +
	"\tHandshake\x12#.weknora.plugin.v1.HandshakeRequest\x1a$.weknora.plugin.v1.HandshakeResponse\x12M\n" +
	"\x06Health\x12 .weknora.plugin.v1.HealthRequest\x1a!.weknora.plugin.v1.HealthResponse\x12S\n" +
	"\x06Search\x12#.weknora.plugin.v1.WebSearchRequest\x1a$.weknora.plugin.v1.WebSearchResponseB<Z:github.com/Tencent/WeKnora/pkg/pluginapi/proto;pluginprotob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),   // 0: weknora.plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil),  // 1: weknora.plugin.v1.HandshakeResponse
	(*HealthRequest)(nil),      // 2: weknora.plugin.v1.HealthRequest
	(*HealthResponse)(nil),     // 3: weknora.plugin.v1.HealthResponse
	(*Cursor)(nil),             // 4: weknora.plugin.v1.Cursor
	(*DataSourceRequest)(nil),  // 5: weknora.plugin.v1.DataSourceRequest
	(*Resource)(nil),           // 6: weknora.plugin.v1.Resource
	(*FetchedItem)(nil),        // 7: weknora.plugin.v1.FetchedItem
	(*DataSourceResponse)(nil), // 8: weknora.plugin.v1.DataSourceResponse
	(*ParserRequest)(nil),      // 9: weknora.plugin.v1.ParserRequest
	(*ParserImageRef)(nil),     // 10: weknora.plugin.v1.ParserImageRef
	(*ParserResponse)(nil),     // 11: weknora.plugin.v1.ParserResponse
	(*WebSearchRequest)(nil),   // 12: weknora.plugin.v1.WebSearchRequest
	(*WebSearchResult)(nil),    // 13: weknora.plugin.v1.WebSearchResult
	(*WebSearchResponse)(nil),  // 14: weknora.plugin.v1.WebSearchResponse
	nil,                        // 15: weknora.plugin.v1.Resource.MetadataEntry
	nil,                        // 16: weknora.plugin.v1.FetchedItem.MetadataEntry
	nil,                        // 17: weknora.plugin.v1.ParserRequest.ParserEngineOverridesEntry
	nil,                        // 18: weknora.plugin.v1.ParserResponse.MetadataEntry
	nil,                        // 19: weknora.plugin.v1.WebSearchRequest.ExtraConfigEntry
	(*structpb.Struct)(nil),    // 20: google.protobuf.Struct
}
var file_plugin_proto_depIdxs = []int32{
	20, // 0: weknora.plugin.v1.DataSourceRequest.config:type_name -> google.protobuf.Struct
	4,  // 1: weknora.plugin.v1.DataSourceRequest.cursor:type_name -> weknora.plugin.v1.Cursor
	15, // 2: weknora.plugin.v1.Resource.metadata:type_name -> weknora.plugin.v1.Resource.MetadataEntry
	16, // 3: weknora.plugin.v1.FetchedItem.metadata:type_name -> weknora.plugin.v1.FetchedItem.MetadataEntry
	6,  // 4: weknora.plugin.v1.DataSourceResponse.resources:type_name -> weknora.plugin.v1.Resource
	7,  // 5: weknora.plugin.v1.DataSourceResponse.items:type_name -> weknora.plugin.v1.FetchedItem
	4,  // 6: weknora.plugin.v1.DataSourceResponse.cursor:type_name -> weknora.plugin.v1.Cursor
	17, // 7: weknora.plugin.v1.ParserRequest.parser_engine_overrides:type_name -> weknora.plugin.v1.ParserRequest.ParserEngineOverridesEntry
	10, // 8: weknora.plugin.v1.ParserResponse.image_refs:type_name -> weknora.plugin.v1.ParserImageRef
	18, // 9: weknora.plugin.v1.ParserResponse.metadata:type_name -> weknora.plugin.v1.ParserResponse.MetadataEntry
	19, // 10: weknora.plugin.v1.WebSearchRequest.extra_config:type_name -> weknora.plugin.v1.WebSearchRequest.ExtraConfigEntry
	13, // 11: weknora.plugin.v1.WebSearchResponse.results:type_name -> weknora.plugin.v1.WebSearchResult
	0,  // 12: weknora.plugin.v1.DataSourcePlugin.Handshake:input_type -> weknora.plugin.v1.HandshakeRequest
	2,  // 13: weknora.plugin.v1.DataSourcePlugin.Health:input_type -> weknora.plugin.v1.HealthRequest
	5,  // 14: weknora.plugin.v1.DataSourcePlugin.Validate:input_type -> weknora.plugin.v1.DataSourceRequest
	5,  // 15: weknora.plugin.v1.DataSourcePlugin.ListResources:input_type -> weknora.plugin.v1.DataSourceRequest
	5,  // 16: weknora.plugin.v1.DataSourcePlugin.ResolveResourceAncestors:input_type -> weknora.plugin.v1.DataSourceRequest
	5,  // 17: weknora.plugin.v1.DataSourcePlugin.FetchAll:input_type -> weknora.plugin.v1.DataSourceRequest
	5,  // 18: weknora.plugin.v1.DataSourcePlugin.FetchIncremental:input_type -> weknora.plugin.v1.DataSourceRequest
	5,  // 19: weknora.plugin.v1.DataSourcePlugin.FetchAllStream:input_type -> weknora.plugin.v1.DataSourceRequest
	5,  // 20: weknora.plugin.v1.DataSourcePlugin.FetchIncrementalStream:input_type -> weknora.plugin.v1.DataSourceRequest
	0,  // 21: weknora.plugin.v1.ParserPlugin.Handshake:input_type -> weknora.plugin.v1.HandshakeRequest
	2,  // 22: weknora.plugin.v1.ParserPlugin.Health:input_type -> weknora.plugin.v1.HealthRequest
	9,  // 23: weknora.plugin.v1.ParserPlugin.Parse:input_type -> weknora.plugin.v1.ParserRequest
	0,  // 24: weknora.plugin.v1.WebSearchPlugin.Handshake:input_type -> weknora.plugin.v1.HandshakeRequest
	2,  // 25: weknora.plugin.v1.WebSearchPlugin.Health:input_type -> weknora.plugin.v1.HealthRequest
	12, // 26: weknora.plugin.v1.WebSearchPlugin.Search:input_type -> weknora.plugin.v1.WebSearchRequest
	1,  // 27: weknora.plugin.v1.DataSourcePlugin.Handshake:output_type -> weknora.plugin.v1.HandshakeResponse
	3,  // 28: weknora.plugin.v1.DataSourcePlugin.Health:output_type -> weknora.plugin.v1.HealthResponse
	8,  // 29: weknora.plugin.v1.DataSourcePlugin.Validate:output_type -> weknora.plugin.v1.DataSourceResponse
	8,  // 30: weknora.plugin.v1.DataSourcePlugin.ListResources:output_type -> weknora.plugin.v1.DataSourceResponse
	8,  // 31: weknora.plugin.v1.DataSourcePlugin.ResolveResourceAncestors:output_type -> weknora.plugin.v1.DataSourceResponse
	8,  // 32: weknora.plugin.v1.DataSourcePlugin.FetchAll:output_type -> weknora.plugin.v1.DataSourceResponse
	8,  // 33: weknora.plugin.v1.DataSourcePlugin.FetchIncremental:output_type -> weknora.plugin.v1.DataSourceResponse
	8,  // 34: weknora.plugin.v1.DataSourcePlugin.FetchAllStream:output_type -> weknora.plugin.v1.DataSourceResponse
	8,  // 35: weknora.plugin.v1.DataSourcePlugin.FetchIncrementalStream:output_type -> weknora.plugin.v1.DataSourceResponse
	1,  // 36: weknora.plugin.v1.ParserPlugin.Handshake:output_type -> weknora.plugin.v1.HandshakeResponse
	3,  // 37: weknora.plugin.v1.ParserPlugin.Health:output_type -> weknora.plugin.v1.HealthResponse
	11, // 38: weknora.plugin.v1.ParserPlugin.Parse:output_type -> weknora.plugin.v1.ParserResponse
	1,  // 39: weknora.plugin.v1.WebSearchPlugin.Handshake:output_type -> weknora.plugin.v1.HandshakeResponse
	3,  // 40: weknora.plugin.v1.WebSearchPlugin.Health:output_type -> weknora.plugin.v1.HealthResponse
	14, // 41: weknora.plugin.v1.WebSearchPlugin.Search:output_type -> weknora.plugin.v1.WebSearchResponse
	27, // [27:42] is the sub-list for method output_type
	12, // [12:27] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
